### ISSUE TITLE
doesnt install anymore

### ISSUE THREAD

**Issue by contra** [mdelete/node-tesseract-native#6]
iojs 1.5.1

```
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/tesseract_native/node-tesseract-native.o
../node-tesseract-native.cc:16:16: error: expected class
      name
class OcrEio : ObjectWrap
               ^
../node-tesseract-native.cc:44:34: error: unknown type
      name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> New(const Arguments& args)
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/contra/.node-gyp/1.5.1/deps/v8/include/v8.h:133:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-tesseract-native.cc:65:34: error: unknown type
      name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Ocr(const Arguments& args)
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/contra/.node-gyp/1.5.1/deps/v8/include/v8.h:133:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-tesseract-native.cc:187:23: error: unknown type
      name 'uv_work_t'
  static void EIO_Ocr(uv_work_t *req)
                      ^
../node-tesseract-native.cc:217:28: error: unknown type
      name 'uv_work_t'
  static void EIO_AfterOcr(uv_work_t *req, int status)
                           ^
../node-tesseract-native.cc:23:55: error: cannot
      initialize a parameter of type 'v8::Isolate *'
      with an lvalue of type 'Handle<v8::Value> (const
      v8::internal::Arguments &)'
  ...t = FunctionTemplate::New(New);
                               ^~~
/Users/contra/.node-gyp/1.5.1/deps/v8/include/v8.h:3824:16: note:
      passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../node-tesseract-native.cc:25:42: error: 'New' is a
      private member of
      'v8::PersistentBase<v8::FunctionTemplate>'
    s_ct = Persistent<FunctionTemplate>::New(t);
                                         ^
/Users/contra/.node-gyp/1.5.1/deps/v8/include/v8.h:637:23: note:
      declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../node-tesseract-native.cc:25:12: error: too few
      arguments to function call, expected 2, have 1;
      did you mean '::OcrEio::New'?
    s_ct = Persistent<FunctionTemplate>::New(t);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           ::OcrEio::New
../node-tesseract-native.cc:44:24: note:
      '::OcrEio::New' declared here
  static Handle<Value> New(const Arguments& args)
                       ^
../node-tesseract-native.cc:26:9: error: member
      reference type 'Persistent<v8::FunctionTemplate>'
      is not a pointer; maybe you meant to use '.'?
    s_ct->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~^~
        .
../node-tesseract-native.cc:26:11: error: no member
      named 'InstanceTemplate' in
      'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate>
      >'
    s_ct->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~  ^
../node-tesseract-native.cc:27:9: error: member
      reference type 'Persistent<v8::FunctionTemplate>'
      is not a pointer; maybe you meant to use '.'?
    s_ct->SetClassName(String::NewSymbol("OcrEio"));
    ~~~~^~
        .
../node-tesseract-native.cc:27:11: error: no member
      named 'SetClassName' in
      'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate>
      >'
    s_ct->SetClassName(String::NewSymbol("OcrEio"));
    ~~~~  ^
../node-tesseract-native.cc:27:32: error: no member
      named 'NewSymbol' in 'v8::String'
    s_ct->SetClassName(String::NewSymbol("OcrEio"));
                       ~~~~~~~~^
../node-tesseract-native.cc:29:31: error: no viable
      conversion from 'Persistent<v8::FunctionTemplate>'
      to 'v8::Handle<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(s_ct, "ocr", Ocr);
                              ^~~~
/Users/contra/.node-gyp/1.5.1/deps/v8/include/v8.h:214:26: note:
      candidate constructor (the implicit copy
      constructor) not viable: no known conversion from
      'Persistent<v8::FunctionTemplate>' to 'const
      v8::Handle<v8::FunctionTemplate> &' for 1st
      argument
template <class T> class Handle {
                         ^
/Users/contra/.node-gyp/1.5.1/deps/v8/include/v8.h:214:26: note:
      candidate constructor (the implicit move
      constructor) not viable: no known conversion from
      'Persistent<v8::FunctionTemplate>' to
      'v8::Handle<v8::FunctionTemplate> &&' for 1st
      argument
template <class T> class Handle {
                         ^
/Users/contra/.node-gyp/1.5.1/deps/v8/include/v8.h:231:32: note:
      candidate template ignored: could not match
      'Handle' against 'Persistent'
  template <class S> V8_INLINE Handle(Handle<S> that)
                               ^
/Users/contra/.node-gyp/1.5.1/src/node.h:224:72: note:
      passing argument to parameter 'recv' here
  ...recv,
     ^
../node-tesseract-native.cc:31:25: error: no member
      named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("OcrEio"), s_c...
                ~~~~~~~~^
../node-tesseract-native.cc:46:17: error: calling a
      protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/contra/.node-gyp/1.5.1/deps/v8/include/v8.h:878:13: note:
      declared protected here
  V8_INLINE HandleScope() {}
            ^
../node-tesseract-native.cc:48:9: error: no member named
      'Wrap' in 'OcrEio'
    oe->Wrap(args.This());
    ~~  ^
../node-tesseract-native.cc:48:18: error: member access
      into incomplete type 'const
      v8::internal::Arguments'
    oe->Wrap(args.This());
                 ^
/Users/contra/.node-gyp/1.5.1/deps/v8/include/v8.h:133:7: note:
      forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../node-tesseract-native.cc:49:18: error: no member
      named 'Close' in 'v8::HandleScope'
    return scope.Close(args.This());
           ~~~~~ ^
fatal error: too many errors emitted, stopping now
      [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/tesseract_native/node-tesseract-native.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/contra/.nvm/versions/io.js/v1.5.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/contra/.nvm/versions/io.js/v1.5.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/contra/Desktop/ocr/node_modules/tesseract_native
gyp ERR! node -v v1.5.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/contra/.nvm/versions/io.js/v1.5.1/bin/iojs" "/Users/contra/.nvm/versions/io.js/v1.5.1/bin/npm" "install" "tesseract_native"
npm ERR! node v1.5.1
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE

npm ERR! tesseract_native@0.4.1 preinstall: `node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tesseract_native@0.4.1 preinstall script 'node-gyp configure && node-gyp build'.
npm ERR! This is most likely a problem with the tesseract_native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls tesseract_native
npm ERR! There is likely additional logging output above.
```

**Comment by mdelete** [comment]
Yeah, sorry. With iojs and node 0.12.x the C++ API had major changes. I'll try to fix that soon.

**Comment by mdelete** [comment]
The node12 branch of this repo now builds with node 0.12.x, I didn't try iojs but they have rejoined with node anyways.
